### ISSUE TITLE
Issue-Change layout algorithm

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#14]
Automated Review Comments
Issues in examples/prototype.rs:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in src/layout.rs:
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (69, 'TODO found')
Issues in src/widgets/block.rs:
  - (11, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
