### ISSUE TITLE
Issue-Add support for multi line sparkline

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#21]
Automated Review Comments
Issues in examples/prototype.rs:
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in src/widgets/sparkline.rs:
  - (35, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (69, 'Hardcoded string found')

**Comment by doraemon-35** [comment]
I got it.
