### ISSUE TITLE
Issue-Cleanup code and add chart widget

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#27]
Automated Review Comments
Issues in examples/prototype.rs:
  - (84, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
Issues in src/layout.rs:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
Issues in src/terminal.rs:
  - (41, 'Hardcoded string found')
Issues in src/widgets/block.rs:
  - (21, 'Line exceeds 80 characters')
Issues in src/widgets/chart.rs:
  - (77, 'Line exceeds 80 characters')
Issues in src/widgets/mod.rs:
  - (36, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in src/widgets/sparkline.rs:
  - (30, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
Issues in src/widgets/text.rs:
  - (56, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
