### ISSUE TITLE
Issue-Remove cache system and add unicode segmentation

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#29]
Automated Review Comments
Issues in examples/block.rs:
  - (20, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in examples/prototype.rs:
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
Issues in src/buffer.rs:
  - (21, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
Issues in src/terminal.rs:
  - (32, 'Hardcoded string found')
Issues in src/widgets/block.rs:
  - (29, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
Issues in src/widgets/gauge.rs:
  - (58, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
Issues in src/widgets/list.rs:
  - (37, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
Issues in src/widgets/sparkline.rs:
  - (32, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
Issues in src/widgets/text.rs:
  - (33, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
