### ISSUE TITLE
Issue-Cache layout and performance fixes

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#33]
Automated Review Comments
Issues in examples/prototype.rs:
  - (17, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
Issues in src/widgets/chart.rs:
  - (11, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')

**Comment by angel-1x** [comment]
I got it.
