### ISSUE TITLE
Issue-Fix clippy warnings

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#35]
Automated Review Comments
Issues in examples/block.rs:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in examples/prototype.rs:
  - (17, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
Issues in src/widgets/sparkline.rs:
  - (7, 'Hardcoded string found')

**Comment by angel-1x** [comment]
I got it.
