### ISSUE TITLE
Issue-Update chart widget and fix colors in all widgets

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#37]
Automated Review Comments
Issues in examples/prototype.rs:
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
Issues in src/buffer.rs:
  - (27, 'Line exceeds 80 characters')
Issues in src/style.rs:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
Issues in src/widgets/block.rs:
  - (73, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
Issues in src/widgets/chart.rs:
  - (58, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
Issues in src/widgets/gauge.rs:
  - (23, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in src/widgets/sparkline.rs:
  - (18, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')

**Comment by doraemon-35** [comment]
I got it.
