### ISSUE TITLE
Issue-Add features to the list widgets

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#39]
Automated Review Comments
Issues in examples/prototype.rs:
  - (17, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in src/widgets/list.rs:
  - (39, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')

**Comment by angel-1x** [comment]
I got it.
