### ISSUE TITLE
Issue-Small improvements

### ISSUE THREAD

**Issue by drone-1x** [drone-1x/solana-1#41]
Automated Review Comments
Issues in examples/prototype.rs:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
Issues in src/buffer.rs:
  - (11, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
Issues in src/widgets/barchart.rs:
  - (41, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
Issues in src/widgets/sparkline.rs:
  - (12, 'Hardcoded string found')

**Comment by angel-1x** [comment]
I got it.
